Fix "Advanced Installation" instructions.
This commit harmonizes the installation instructions with those in Dockerfile.
In particular, the following issues are addressed:

1. Remove assumption that using existing jupyter installation will work.

  Using my existing installation yielded the following error:

    [I 11:07:24.555 NotebookApp] KernelRestarter: restarting kernel (1/5)
    WARNING:root:kernel 158c8945-e402-4607-a9d3-a0558ebd02a0 restarted
    ERROR: LoadError: UndefVarError: Compat not defined
    Stacktrace:
     [1] include at ./boot.jl:317 [inlined]
     [2] include_relative(::Module, ::String) at ./loading.jl:1038
     [3] include(::Module, ::String) at ./sysimg.jl:29
     [4] exec_options(::Base.JLOptions) at ./client.jl:229
     [5] _start() at ./client.jl:421
    in expression starting at /scratch/fsaad/.julia/packages/IJulia/fDY4W/src/kernel.jl:2

  We should not expect that an existing Jupyter installation will be of
  the right version or have the right dependencies and it is safer to have
  a specialized Jupyter installation for Gen.

2. Remove assumption that IJulia will install Jupyter

    If you do not already have a `jupyter` installation, the IJulia package will install one by itself:
    ```
    JULIA_PROJECT=$(pwd) julia -e 'using Pkg; Pkg.build("IJulia")'
    ```

  According to the IJulia documentation, building IJulia does not install
  Jupyter. Instead, one needs to run the `notebook()` command, which will
  then create a Conda environment (in `~/.julia/Conda`) that contains a
  fresh install of Jupyter.

  However, since we already require the user to install Matplotlib (and
  optionally Tensorflow) in a new Python 3 virtual environment, it would be
  best to unify all the Python dependencies to a single location, which is
  the next item.

3. Unify Python installation for Jupyter, Matplotlib, and Tensorflow.

  It is easiest to have a single Python 3 virtual environment which manages
  all the Python stuff, as opposed to relying on existing installations
  or mixing the Julia-specific Conda environment with a separate virtual
  environment.

  One option would be to install Matplotlib and Tensorflow in the Conda created
  by IJulia (in `~/.julia/Conda`) but that approach was too complicated.

  Unfortunately there does not appear to be an ideal way to decouple Julia from
  Python so a single virtual environment seems to be the best solution.